name: sasrec
channels:
  - pytorch
  - conda-forge
  - nodefaults
dependencies:
  - python=3.9.2
  - pip
  - setuptools
  - ipykernel=5.5.3
  - numpy=1.20.2
  - scipy=1.6.3
  - numba=0.53.1
  - pandas=1.2.4
  - matplotlib=3.4.1
  - seaborn=0.11.1
  - scikit-learn=0.24.2
  - tqdm=4.60.0
  # PyTorch part
  - pytorch=1.8.1
  - cudatoolkit=11.1.1
  # WANDB dependencies (forcing install from conda instead of pip)
  - Click>=7.0
  - GitPython>=1.0.0
  - PyYAML
  - configparser>=3.8.1
  - docker-pycreds>=0.4.0
  - pathtools
  - promise<3,>=2.0
  - protobuf>=3.12.0
  - psutil>=5.0.0
  - python-dateutil>=2.6.1
  - requests<3,>=2.0.0
  - sentry-sdk>=0.4.0
  - shortuuid>=0.5.0
  - six>=1.13.0
  - subprocess32>=3.5.3  
  - pip:
    - wandb==0.10.31